[package]
name = "blake2ya-native"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2ya = "1.0"
blake2b-rs = "0.2"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "main"
harness = false
